app:
  title: "Language Translation & Grammar Correction"
  description: "A Streamlit app for translating text between different languages and correcting grammar."
  version: "1.0.0"
  authors:
    - name: "Your Name"
      email: "your.email@example.com"
  dependencies:
    - streamlit
    - transformers
    - torch