name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }} # replace with your token if not using the default

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Use a compatible Python version

    - name: Install Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install additional build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3-dev cargo

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install --no-cache-dir -r requirements.txt

    - name: Run model training or inference
      run: |
        python app.py  # Make sure to run with python

    - name: Add output files to git
      run: |
        git config --local user.email "nassarmn216@yahoo.com"
        git config --local user.name "NaMN21" 
        git commit -m "Update model output files" || echo "No changes to commit"

    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin HEAD:main

    - name: Run tests
      run: pytest  # Add your test command here
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # or your personal access token
    
    permissions:
      contents: write # Grant write access to the repository contents
